version: '3.5'

services:
  backend: 
    build: ./backend/
    ports: 
     - 8000:8000 
    container_name: backend-2.9
    volumes: 
     - ./logs.txt:/app/logs.txt
    environment:
     - FRONT_URL=http://192.168.1.50:5000
     - REDIS=redis
     - REDIS_PORT=6379
     - DB_USERNAME=devops
     - DB_PASSWORD=testing
     - DB_HOST=postgres
  frontend: 
    build: ./frontend/
    ports: 
     - 5000:5000
    environment:
     - API_URL=http://192.168.1.50:8000
    container_name: frontend-2.9
  redis: 
    image: redis:latest
    ports:
     - 6379:6379
    volumes:
     - ./data:/data
    container_name: redis-2.9
  postgres:
    image: postgres:latest
    volumes: 
     - ./database:/var/lib/postgresql/data
    environment:
     - POSTGRES_PASSWORD=testing
     - POSTGRES_USER=devops
    container_name: postgres-2.9
volumes: 
   database:
   data:
