version: '3.5'

services:
  backend: 
    build: ./backend/
    ports: 
     - 8000:8000 
    container_name: backend-2.3
    volumes: 
     - ./logs.txt:/app/logs.txt
    environment:
     - FRONT_URL=http://192.168.1.50:5000 
  frontend: 
    build: ./frontend/
    ports: 
     - 5000:5000
    container_name: frontend-2.3

